// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGe5J4uys7jpGTjVXQp8x5ZdDkhmIsi8M',
    appId: '1:1083998051434:web:a499c385440126265ffe13',
    messagingSenderId: '1083998051434',
    projectId: 'retirement-4e527',
    authDomain: 'retirement-4e527.firebaseapp.com',
    storageBucket: 'retirement-4e527.firebasestorage.app',
    measurementId: 'G-M5JENFNHFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOtx5TwW7BTz4jGwZDOB4C6mr1CgoNoC4',
    appId: '1:1083998051434:android:24bdae5f4fe8f4985ffe13',
    messagingSenderId: '1083998051434',
    projectId: 'retirement-4e527',
    storageBucket: 'retirement-4e527.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDossYQowHZAosEcIYyH_W8IZEf9CzM-I',
    appId: '1:1083998051434:ios:9e6bda8a1d3cb69f5ffe13',
    messagingSenderId: '1083998051434',
    projectId: 'retirement-4e527',
    storageBucket: 'retirement-4e527.firebasestorage.app',
    iosClientId: '1083998051434-e0mj4vna2ugv4t1jhsk8pnujrkfgtnhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.retierment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDossYQowHZAosEcIYyH_W8IZEf9CzM-I',
    appId: '1:1083998051434:ios:9e6bda8a1d3cb69f5ffe13',
    messagingSenderId: '1083998051434',
    projectId: 'retirement-4e527',
    storageBucket: 'retirement-4e527.firebasestorage.app',
    iosClientId: '1083998051434-e0mj4vna2ugv4t1jhsk8pnujrkfgtnhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.retierment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGe5J4uys7jpGTjVXQp8x5ZdDkhmIsi8M',
    appId: '1:1083998051434:web:b902b40c64f23e425ffe13',
    messagingSenderId: '1083998051434',
    projectId: 'retirement-4e527',
    authDomain: 'retirement-4e527.firebaseapp.com',
    storageBucket: 'retirement-4e527.firebasestorage.app',
    measurementId: 'G-E8G7P5CPBT',
  );
}
